# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
title: Next Generation Scoop
email: io2oi@yahoo.co.kr
description: > # this means to ignore newlines until "baseurl:"
  병철이의 떠먹여주는 생명과학
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://io2oi.github.io" # the base hostname & protocol for your site
github_username:  io2oi
facebook: io2oi

# Build settings
markdown: kramdown
highlighter: rouge